// Generated by triad/scripts/gen_legion.ts from Legion (MIT; see triad/LEGION-NOTICE.md). Do not edit.
export const ROSTER_GAP_CONFIG: any = {
 "gap_analysis": {
  "version": "1.0",
  "agent_limit": 52,
  "role_categories": {
   "sre_devops": {
    "priority": "critical",
    "description": "Site Reliability Engineering and DevOps capabilities",
    "roles": {
     "sre_reliability_engineer": {
      "description": "Formal SRE with SLOs, error budgets, and reliability focus",
      "required_capabilities": [
       "slo_management",
       "error_budgets",
       "incident_response",
       "reliability_engineering"
      ],
      "coverage_indicators": [
       "engineering-infrastructure-devops",
       "engineering-infrastructure-devops"
      ]
     },
     "chaos_engineer": {
      "description": "Chaos engineering and failure injection testing",
      "required_capabilities": [
       "chaos_experiments",
       "failure_injection",
       "resilience_testing",
       "game_days"
      ],
      "coverage_indicators": [
       "testing-performance-benchmarker"
      ]
     },
     "platform_engineer": {
      "description": "Internal developer platform and tooling",
      "required_capabilities": [
       "developer_platforms",
       "internal_tooling",
       "self_service_infrastructure"
      ],
      "coverage_indicators": [
       "engineering-infrastructure-devops"
      ]
     },
     "observability_engineer": {
      "description": "Monitoring, logging, tracing, and observability",
      "required_capabilities": [
       "distributed_tracing",
       "metrics_collection",
       "log_aggregation",
       "alerting_systems"
      ],
      "coverage_indicators": [
       "engineering-infrastructure-devops",
       "data-analytics-engineer"
      ]
     }
    }
   },
   "security": {
    "priority": "critical",
    "description": "Security engineering and compliance capabilities",
    "roles": {
     "security_engineer": {
      "description": "Dedicated security engineer with OWASP/STRIDE expertise",
      "required_capabilities": [
       "owasp_top_10",
       "stride_threat_modeling",
       "secure_code_review",
       "vulnerability_assessment"
      ],
      "coverage_indicators": [
       "engineering-security-engineer"
      ]
     },
     "compliance_auditor": {
      "description": "Compliance and regulatory audit capabilities",
      "required_capabilities": [
       "regulatory_compliance",
       "audit_preparation",
       "policy_enforcement",
       "risk_assessment"
      ],
      "coverage_indicators": [
       "support-legal-compliance-checker"
      ]
     },
     "penetration_tester": {
      "description": "Penetration testing and security validation",
      "required_capabilities": [
       "penetration_testing",
       "exploit_development",
       "red_team_operations"
      ],
      "coverage_indicators": [
       "testing-api-tester"
      ]
     },
     "pii_specialist": {
      "description": "PII protection and data privacy specialist",
      "required_capabilities": [
       "data_privacy",
       "pii_detection",
       "gdpr_compliance",
       "data_classification"
      ],
      "coverage_indicators": [
       "support-legal-compliance-checker"
      ]
     }
    }
   },
   "data_ai": {
    "priority": "important",
    "description": "Data science, ML, and AI capabilities",
    "roles": {
     "data_scientist": {
      "description": "Statistical modeling, experimental design, and data analysis",
      "required_capabilities": [
       "statistical_modeling",
       "hypothesis_testing",
       "experimental_design",
       "data_visualization"
      ],
      "coverage_indicators": [
       "data-analytics-engineer"
      ]
     },
     "ml_engineer": {
      "description": "Machine learning model development and deployment",
      "required_capabilities": [
       "ml_model_training",
       "model_deployment",
       "feature_engineering",
       "ml_ops"
      ],
      "coverage_indicators": [
       "engineering-ai-engineer"
      ]
     },
     "data_engineer": {
      "description": "Data pipeline engineering and infrastructure",
      "required_capabilities": [
       "etl_pipelines",
       "data_warehousing",
       "data_quality",
       "data_governance"
      ],
      "coverage_indicators": [
       "data-analytics-engineer"
      ]
     }
    }
   },
   "engineering": {
    "priority": "important",
    "description": "Core software engineering capabilities",
    "roles": {
     "senior_developer": {
      "description": "Senior-level full-stack development",
      "required_capabilities": [
       "architecture_design",
       "code_review",
       "mentoring",
       "technical_leadership"
      ],
      "coverage_indicators": [
       "engineering-senior-developer"
      ]
     },
     "backend_architect": {
      "description": "Backend system architecture and API design",
      "required_capabilities": [
       "api_design",
       "database_architecture",
       "microservices",
       "distributed_systems"
      ],
      "coverage_indicators": [
       "engineering-backend-architect"
      ]
     },
     "frontend_specialist": {
      "description": "Advanced frontend development and architecture",
      "required_capabilities": [
       "component_architecture",
       "state_management",
       "performance_optimization",
       "accessibility"
      ],
      "coverage_indicators": [
       "engineering-frontend-developer"
      ]
     }
    }
   },
   "operations": {
    "priority": "nice_to_have",
    "description": "Operational support and maintenance capabilities",
    "roles": {
     "incident_responder": {
      "description": "24/7 incident response and on-call management",
      "required_capabilities": [
       "incident_management",
       "on_call_rotation",
       "war_room_coordination",
       "post_mortems"
      ],
      "coverage_indicators": [
       "engineering-infrastructure-devops"
      ]
     },
     "runbook_maintainer": {
      "description": "Operational runbook and procedure documentation",
      "required_capabilities": [
       "runbook_authoring",
       "procedure_documentation",
       "operational_readiness",
       "knowledge_base"
      ],
      "coverage_indicators": [
       "project-management-studio-operations"
      ]
     }
    }
   }
  },
  "scoring": {
   "full_coverage": 1,
   "partial_coverage": 0.5,
   "minimal_coverage": 0.2,
   "no_coverage": 0,
   "weight_by_role_count": {
    "single_agent": 1,
    "two_agents": 1.2,
    "three_or_more": 1.3
   }
  },
  "severity": {
   "critical": {
    "min_gap_score": 0.8,
    "description": "Blocks production use, immediate attention required",
    "color": "#FF0000",
    "action": "MUST address in current phase"
   },
   "high": {
    "min_gap_score": 0.5,
    "description": "Significant impact on production readiness",
    "color": "#FF6600",
    "action": "SHOULD address in current phase"
   },
   "medium": {
    "min_gap_score": 0.3,
    "description": "Moderate impact, address in next milestone",
    "color": "#FFCC00",
    "action": "Address in v5.1 or v6.0"
   },
   "low": {
    "min_gap_score": 0,
    "description": "Nice to have, address when convenient",
    "color": "#009900",
    "action": "Address as time permits"
   }
  },
  "intent_teams_to_check": {
   "harden": {
    "description": "Security audit with Testing + Security divisions",
    "required_agents": [
     "testing-qa-verification-specialist",
     "engineering-security-engineer",
     "testing-api-tester"
    ]
   },
   "document": {
    "description": "Documentation generation",
    "required_agents": [
     "product-technical-writer",
     "engineering-frontend-developer"
    ]
   },
   "security-only": {
    "description": "Security-only review audit",
    "required_agents": [
     "engineering-security-engineer",
     "testing-api-tester"
    ]
   }
  },
  "replacement_candidates": {
   "low_usage": [
    {
     "agent_id": "marketing-tiktok-strategist",
     "reason": "Very niche platform, limited applicability",
     "replacement_difficulty": "low"
    },
    {
     "agent_id": "marketing-reddit-community-builder",
     "reason": "Niche platform, can be covered by general social strategist",
     "replacement_difficulty": "low"
    }
   ],
   "overlapping": [
    {
     "agent_id": "testing-tool-evaluator",
     "reason": "Testing-specific, lower priority than core QA agents",
     "replacement_difficulty": "medium"
    }
   ],
   "candidates_for_consolidation": null
  },
  "current_gaps": {
   "missing_referenced_agents": [
    {
     "agent_id": "engineering-security-engineer",
     "referenced_in": [
      "harden intent",
      "security-only intent"
     ],
     "severity": "critical",
     "impact": "harden intent cannot function as designed"
    },
    {
     "agent_id": "product-technical-writer",
     "referenced_in": [
      "document intent"
     ],
     "severity": "high",
     "impact": "document intent uses suboptimal fallback"
    }
   ],
   "coverage_gaps": [
    {
     "role": "sre_reliability_engineer",
     "current_coverage": "partial",
     "covering_agents": [
      "engineering-infrastructure-devops"
     ],
     "gaps": [
      "formal SLO management",
      "chaos engineering",
      "runbook automation"
     ],
     "severity": "medium"
    },
    {
     "role": "security_engineer",
     "current_coverage": "minimal",
     "covering_agents": [
      "testing-api-tester"
     ],
     "gaps": [
      "OWASP Top 10 comprehensive audit",
      "STRIDE threat modeling",
      "secure code review",
      "PII compliance checking"
     ],
     "severity": "high"
    },
    {
     "role": "data_scientist",
     "current_coverage": "partial",
     "covering_agents": [
      "data-analytics-engineer",
      "engineering-ai-engineer"
     ],
     "gaps": [
      "statistical modeling",
      "hypothesis testing",
      "experimental design",
      "A/B test analysis"
     ],
     "severity": "medium"
    }
   ]
  },
  "report_generation": {
   "include_agent_inventory": true,
   "include_coverage_matrix": true,
   "include_recommendations": true,
   "include_limit_analysis": true,
   "severity_order": [
    "critical",
    "high",
    "medium",
    "low"
   ]
  },
  "integrations": {
   "catalog_file": "skills/agent-registry/CATALOG.md",
   "intent_teams_file": ".planning/config/intent-teams.yaml",
   "output_directory": ".planning/phases/40-roster-gap-analysis"
  }
 }
}

export const INTENT_TEAMS: any = {
 "intents": {
  "harden": {
   "description": "Security audit with Testing + Security divisions",
   "agents": {
    "primary": [
     "testing-qa-verification-specialist",
     "engineering-security-engineer"
    ],
    "secondary": [
     "testing-api-tester"
    ]
   },
   "domains": [
    "security",
    "owasp",
    "stride",
    "vulnerability-assessment"
   ],
   "mode": "ad_hoc"
  },
  "document": {
   "description": "Generate documentation without implementation",
   "agents": {
    "primary": [
     "product-technical-writer"
    ],
    "secondary": [
     "engineering-frontend-developer"
    ]
   },
   "filter": {
    "include_task_types": [
     "documentation",
     "readme",
     "api-docs",
     "guides"
    ],
    "exclude_task_types": [
     "implementation",
     "code",
     "testing"
    ]
   },
   "mode": "filter_plans"
  },
  "skip-frontend": {
   "description": "Exclude frontend/UI tasks",
   "filter": {
    "exclude_agents": [
     "engineering-frontend-developer",
     "design-ui-designer"
    ],
    "exclude_file_patterns": [
     "src/frontend/**",
     "*.tsx",
     "*.jsx",
     "*.css",
     "*.scss",
     "*.vue"
    ],
    "exclude_task_types": [
     "ui-components",
     "frontend-architecture",
     "styling"
    ]
   },
   "mode": "filter_plans"
  },
  "skip-backend": {
   "description": "Exclude backend/API tasks",
   "filter": {
    "exclude_agents": [
     "engineering-backend-architect",
     "engineering-infrastructure-devops"
    ],
    "exclude_file_patterns": [
     "src/api/**",
     "src/backend/**",
     "*.route.ts",
     "prisma/schema.prisma"
    ],
    "exclude_task_types": [
     "api-endpoints",
     "database-schema",
     "backend-logic"
    ]
   },
   "mode": "filter_plans"
  },
  "security-only": {
   "description": "Security-only review audit",
   "agents": {
    "primary": [
     "engineering-security-engineer"
    ],
    "secondary": [
     "testing-api-tester"
    ]
   },
   "domains": [
    "security",
    "owasp",
    "stride",
    "authentication",
    "authorization"
   ],
   "mode": "filter_review"
  }
 },
 "task_types": {
  "documentation": [
   "readme",
   "api-docs",
   "guides",
   "tutorials",
   "comments"
  ],
  "implementation": [
   "feature",
   "bug-fix",
   "refactor",
   "optimization"
  ],
  "testing": [
   "unit-test",
   "integration-test",
   "e2e-test",
   "security-test"
  ],
  "ui-components": [
   "react",
   "vue",
   "angular",
   "svelte",
   "web-components"
  ],
  "frontend-architecture": [
   "routing",
   "state-management",
   "build-config"
  ],
  "api-endpoints": [
   "rest",
   "graphql",
   "grpc",
   "webhook"
  ],
  "database-schema": [
   "migration",
   "model",
   "relation",
   "index"
  ]
 },
 "validation": {
  "mutual_exclusion": [
   {
    "flags": [
     "harden",
     "document"
    ],
    "error": "Cannot use --just-harden and --just-document together. Choose one intent."
   },
   {
    "flags": [
     "document",
     "skip-frontend"
    ],
    "error": "--just-document already excludes implementation; --skip-frontend is redundant."
   },
   {
    "flags": [
     "skip-frontend",
     "skip-backend"
    ],
    "error": "Cannot skip both frontend and backend — nothing to build."
   }
  ],
  "requires_command": [
   {
    "flag": "harden",
    "commands": [
     "build"
    ],
    "error": "--just-harden is only valid for /legion:build"
   },
   {
    "flag": "document",
    "commands": [
     "build"
    ],
    "error": "--just-document is only valid for /legion:build"
   },
   {
    "flag": "skip-frontend",
    "commands": [
     "build"
    ],
    "error": "--skip-frontend is only valid for /legion:build"
   },
   {
    "flag": "skip-backend",
    "commands": [
     "build"
    ],
    "error": "--skip-backend is only valid for /legion:build"
   },
   {
    "flag": "security-only",
    "commands": [
     "review"
    ],
    "error": "--just-security is only valid for /legion:review"
   }
  ],
  "allowed_combinations": [
   {
    "flags": [
     "skip-frontend"
    ],
    "allows": [
     "skip-backend"
    ]
   },
   {
    "flags": [
     "harden"
    ],
    "allows": []
   }
  ]
 },
 "nl_patterns": {
  "harden": {
   "keywords": {
    "security": 1,
    "harden": 1,
    "vulnerabilities": 0.9,
    "owasp": 0.9,
    "audit": 0.7,
    "secure": 0.8,
    "penetration": 0.8,
    "exploit": 0.7,
    "threat": 0.6,
    "stride": 0.8
   },
   "phrases": [
    "harden {the|our|my}? security",
    "run {a}? security audit",
    "fix {the}? vulnerabilities",
    "check for {security}? {issues|problems|vulnerabilities}",
    "security {audit|scan|review}"
   ]
  },
  "document": {
   "keywords": {
    "documentation": 1,
    "docs": 1,
    "document": 0.9,
    "readme": 0.8,
    "write": 0.5,
    "guide": 0.7,
    "api-docs": 0.9,
    "tutorial": 0.6,
    "comments": 0.4
   },
   "phrases": [
    "write {the}? {docs|documentation}",
    "generate {the}? documentation",
    "create {a}? readme",
    "document {the|this}? {code|project|api}"
   ]
  },
  "skip-frontend": {
   "keywords": {
    "backend-only": 1,
    "skip-frontend": 1,
    "no-frontend": 0.9,
    "exclude-ui": 0.8,
    "server-only": 0.7,
    "without-ui": 0.7
   },
   "phrases": [
    "skip {the}? frontend",
    "backend only",
    "no {frontend|ui|client} {code|work|tasks}?",
    "exclude {the}? {frontend|ui}"
   ]
  },
  "skip-backend": {
   "keywords": {
    "frontend-only": 1,
    "skip-backend": 1,
    "no-backend": 0.9,
    "exclude-api": 0.8,
    "client-only": 0.7,
    "without-api": 0.7
   },
   "phrases": [
    "skip {the}? backend",
    "frontend only",
    "no {backend|api|server} {code|work|tasks}?",
    "exclude {the}? {backend|api}"
   ]
  },
  "security-only": {
   "keywords": {
    "security-review": 1,
    "security-audit": 1,
    "security": 0.8,
    "owasp": 0.9,
    "stride": 0.8,
    "authentication": 0.7,
    "authorization": 0.7,
    "vulnerabilities": 0.6
   },
   "phrases": [
    "security {only|review|audit}",
    "review {the}? security",
    "check {for}? {security|auth} {issues|problems}?",
    "audit {the}? {authentication|authorization}"
   ]
  }
 },
 "command_routes": {
  "start": {
   "keywords": {
    "start": 1,
    "initialize": 1,
    "new project": 0.9,
    "setup": 0.8,
    "begin": 0.7,
    "create project": 0.8,
    "init": 0.9
   },
   "phrases": [
    "start {a}? {new}? project",
    "initialize {the|a}? {project|codebase}",
    "set up {a}? {new}? {project|repo}",
    "begin {a}? {new}? project"
   ]
  },
  "plan": {
   "keywords": {
    "plan": 1,
    "decompose": 0.9,
    "break down": 0.8,
    "phase": 0.7,
    "tasks": 0.5,
    "scope": 0.5,
    "requirements": 0.4
   },
   "phrases": [
    "plan {the|next}? phase {\\d+}?",
    "break down phase {\\d+}",
    "decompose {the}? {requirements|work|phase}",
    "create {a}? plan {for}?"
   ]
  },
  "build": {
   "keywords": {
    "build": 1,
    "execute": 0.9,
    "run": 0.6,
    "implement": 0.8,
    "code": 0.5,
    "ship": 0.6,
    "develop": 0.7
   },
   "phrases": [
    "build {it|the plans}?",
    "execute {the}? plans",
    "run {the}? build",
    "implement {the}? {plans|phase|features}"
   ]
  },
  "review": {
   "keywords": {
    "review": 1,
    "test": 0.8,
    "quality": 0.7,
    "check": 0.6,
    "qa": 0.9,
    "verify": 0.7,
    "validate": 0.6,
    "fix": 0.4
   },
   "phrases": [
    "review {the}? {code|changes|work}",
    "run {the}? {tests|review}",
    "check {the}? quality",
    "fix {the|my|our} {tests|testing|test suite}",
    "verify {the}? {work|output|results}"
   ]
  },
  "status": {
   "keywords": {
    "status": 1,
    "progress": 0.9,
    "dashboard": 0.8,
    "where": 0.6,
    "next": 0.5,
    "overview": 0.7
   },
   "phrases": [
    "show {the}? {status|progress|dashboard}",
    "where are we",
    "what's next",
    "how is {the}? {project|phase} going"
   ]
  },
  "quick": {
   "keywords": {
    "quick": 1,
    "one-off": 0.9,
    "ad hoc": 0.9,
    "single": 0.6,
    "fast": 0.5,
    "just do": 0.7
   },
   "phrases": [
    "quick {task|fix|run}",
    "run {a}? {one-off|ad hoc} task",
    "just do {this|it|a}",
    "quick {fix|patch|change}"
   ]
  },
  "advise": {
   "keywords": {
    "advise": 1,
    "advice": 1,
    "consult": 0.9,
    "ask": 0.6,
    "opinion": 0.7,
    "recommend": 0.7,
    "suggest": 0.6
   },
   "phrases": [
    "get advice {on|about}",
    "ask {about|an expert}",
    "consult {on|about}",
    "what do you {think|recommend} about"
   ]
  },
  "explore": {
   "keywords": {
    "explore": 1,
    "research": 0.9,
    "crystallize": 0.9,
    "brainstorm": 0.7,
    "investigate": 0.7,
    "prototype": 0.6,
    "spike": 0.7
   },
   "phrases": [
    "explore {options|ideas|approaches}",
    "research {the|a}? {topic|idea|approach}",
    "crystallize {the|an}? idea",
    "brainstorm {about|on}?",
    "investigate {the|a}? {problem|issue|option}"
   ]
  }
 },
 "context_rules": {
  "no_project": {
   "suggestions": [
    {
     "command": "/legion:start",
     "description": "Initialize a new project",
     "reason": "No project state found — start here"
    },
    {
     "command": "/legion:explore",
     "description": "Explore and crystallize an idea first",
     "reason": "Pre-flight alignment before formal project setup"
    }
   ]
  },
  "just_started": {
   "suggestions": [
    {
     "command": "/legion:plan 1",
     "description": "Plan Phase 1: {phase_name}",
     "reason": "Project initialized, ready for first phase planning"
    },
    {
     "command": "/legion:status",
     "description": "View project dashboard",
     "reason": "Orient yourself with the project overview"
    }
   ]
  },
  "needs_planning": {
   "suggestions": [
    {
     "command": "/legion:plan {next_phase}",
     "description": "Plan Phase {next_phase}: {phase_name}",
     "reason": "Phase {phase} complete and reviewed — move to next phase"
    },
    {
     "command": "/legion:status",
     "description": "View overall progress",
     "reason": "See milestone completion percentage"
    }
   ]
  },
  "planned_not_built": {
   "suggestions": [
    {
     "command": "/legion:build",
     "description": "Execute Phase {phase} plans",
     "reason": "Phase {phase} is planned and ready for execution"
    },
    {
     "command": "/legion:status",
     "description": "Review plan breakdown before building",
     "reason": "Verify plan structure looks correct"
    }
   ]
  },
  "building": {
   "suggestions": [
    {
     "command": "/legion:build",
     "description": "Resume Phase {phase} execution",
     "reason": "Build is in progress — continue where you left off"
    },
    {
     "command": "/legion:status",
     "description": "Check build progress",
     "reason": "See which plans are complete and which remain"
    }
   ]
  },
  "needs_review": {
   "suggestions": [
    {
     "command": "/legion:review",
     "description": "Review Phase {phase} output",
     "reason": "Build complete, quality review is the next step"
    },
    {
     "command": "/legion:status",
     "description": "Check what was built before reviewing",
     "reason": "Orient on build outputs before starting review"
    }
   ]
  },
  "review_in_progress": {
   "suggestions": [
    {
     "command": "/legion:review",
     "description": "Continue Phase {phase} review",
     "reason": "Review cycle is active — continue the process"
    },
    {
     "command": "/legion:status",
     "description": "Check review findings so far",
     "reason": "See current review status and findings"
    }
   ]
  },
  "review_failed": {
   "suggestions": [
    {
     "command": "/legion:build",
     "description": "Fix review findings for Phase {phase}",
     "reason": "Review found issues that need to be addressed"
    },
    {
     "command": "/legion:review",
     "description": "Re-run review after fixes",
     "reason": "Verify fixes resolve the review findings"
    },
    {
     "command": "/legion:status",
     "description": "See what needs fixing",
     "reason": "Review the specific issues found"
    }
   ]
  },
  "phase_complete": {
   "suggestions": [
    {
     "command": "/legion:plan {next_phase}",
     "description": "Plan Phase {next_phase}: {phase_name}",
     "reason": "Phase {phase} complete and reviewed — move to next phase"
    },
    {
     "command": "/legion:status",
     "description": "View overall progress",
     "reason": "See milestone completion percentage"
    }
   ]
  },
  "milestone_complete": {
   "suggestions": [
    {
     "command": "/legion:milestone",
     "description": "Complete and archive the milestone",
     "reason": "All phases done — wrap up the milestone"
    },
    {
     "command": "/legion:status",
     "description": "View final milestone dashboard",
     "reason": "Review everything accomplished in this milestone"
    },
    {
     "command": "/legion:explore",
     "description": "Explore ideas for the next milestone",
     "reason": "Start thinking about what comes next"
    }
   ]
  },
  "unknown": {
   "suggestions": [
    {
     "command": "/legion:status",
     "description": "Check project status",
     "reason": "Project state is ambiguous — orient with the dashboard"
    },
    {
     "command": "/legion:start",
     "description": "Initialize a new project",
     "reason": "If no project exists, start here"
    }
   ]
  }
 }
}
