// Generated by triad/scripts/gen_legion.ts from Legion (MIT; see triad/LEGION-NOTICE.md). Do not edit.
export const SCHEMAS: any = {
 "plan": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Legion Plan Frontmatter",
  "description": "Schema for PLAN.md YAML frontmatter fields",
  "type": "object",
  "required": [
   "phase",
   "plan",
   "wave"
  ],
  "if": {
   "properties": {
    "autonomous": {
     "const": true
    }
   },
   "required": [
    "autonomous"
   ]
  },
  "then": {},
  "else": {
   "required": [
    "agents"
   ]
  },
  "properties": {
   "phase": {
    "oneOf": [
     {
      "type": "integer",
      "minimum": 1
     },
     {
      "type": "string",
      "pattern": "^\\d{2}-[a-z0-9-]+$"
     }
    ],
    "description": "Phase number (legacy) or NN-slug form (current)"
   },
   "plan": {
    "type": "string",
    "pattern": "^\\d{2}-\\d{2}$"
   },
   "wave": {
    "type": "integer",
    "minimum": 0
   },
   "agents": {
    "type": "array",
    "items": {
     "type": "string"
    },
    "minItems": 1,
    "description": "Agent IDs from registry. First entry is primary executor; subsequent entries are co-executors."
   },
   "autonomous": {
    "type": "boolean",
    "default": false
   },
   "depends_on": {
    "type": "array",
    "items": {
     "type": "string",
     "pattern": "^\\d{2}-\\d{2}$"
    }
   },
   "files_modified": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "files_forbidden": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "sequential_files": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "requirements": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "requirement": {
    "type": "string",
    "description": "Singular requirement reference (legacy)"
   },
   "user_setup": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "task": {
       "type": "string"
      },
      "options": {
       "type": "array",
       "items": {
        "type": "string"
       }
      }
     }
    },
    "description": "Pre-execution user setup steps for human-gated tasks"
   },
   "tasks": {
    "type": "integer",
    "description": "Number of tasks in this plan (informational)"
   },
   "expected_artifacts": {
    "type": "array",
    "items": {
     "type": "object",
     "required": [
      "path"
     ],
     "properties": {
      "path": {
       "type": "string"
      },
      "provides": {
       "type": "string"
      },
      "required": {
       "type": "boolean",
       "default": true
      }
     },
     "additionalProperties": false
    }
   },
   "verification_commands": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "must_haves": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
     "truths": {
      "type": "array",
      "items": {
       "type": "string"
      }
     },
     "artifacts": {
      "type": "array",
      "items": {
       "oneOf": [
        {
         "type": "string"
        },
        {
         "type": "object",
         "required": [
          "path"
         ],
         "properties": {
          "path": {
           "type": "string"
          },
          "provides": {
           "type": "string"
          },
          "min_lines": {
           "type": "integer"
          },
          "min_tests": {
           "type": "integer"
          },
          "contains": {
           "oneOf": [
            {
             "type": "string"
            },
            {
             "type": "array",
             "items": {
              "type": "string"
             }
            }
           ]
          }
         },
         "additionalProperties": false
        }
       ]
      }
     },
     "key_links": {
      "type": "array",
      "items": {
       "oneOf": [
        {
         "type": "string"
        },
        {
         "type": "object",
         "required": [
          "from"
         ],
         "properties": {
          "from": {
           "type": "string"
          },
          "to": {
           "type": "string"
          },
          "via": {
           "type": "string"
          },
          "pattern": {
           "type": "string"
          }
         },
         "additionalProperties": false
        }
       ]
      }
     }
    }
   },
   "type": {
    "type": "string"
   },
   "title": {
    "type": "string"
   },
   "recommendation": {
    "type": "object",
    "description": "Optional sidecar of recommendation engine output. Reserved; not required for v6.x/v7.x plans."
   }
  },
  "additionalProperties": false
 },
 "summary": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Legion Plan Summary",
  "description": "Schema for SUMMARY.md structured content",
  "$comment": "Completion Gate: a SUMMARY is complete when (1) it validates against this schema (all required fields present); (2) outcome is exactly one of success|partial|failed — never missing or null; (3) every completed_tasks entry has a terminal status (done|partial|failed|skipped); (4) if any completed_tasks.status == done, its verification_passed field is true; (5) if outcome == success, NO completed_tasks entry has status failed; (6) verification_results array is non-empty when the plan declared verification_commands; (7) user-deferred blocker work keeps outcome partial or failed, never success. Validators MUST fail closed — additional top-level keys are rejected.",
  "type": "object",
  "additionalProperties": false,
  "required": [
   "plan_id",
   "agent",
   "outcome",
   "completed_tasks",
   "files_modified"
  ],
  "properties": {
   "plan_id": {
    "type": "string",
    "pattern": "^\\d{2}-\\d{2}$"
   },
   "agent": {
    "type": "string"
   },
   "outcome": {
    "type": "string",
    "enum": [
     "success",
     "partial",
     "failed"
    ]
   },
   "completed_tasks": {
    "type": "array",
    "items": {
     "type": "object",
     "required": [
      "task_number",
      "description",
      "status"
     ],
     "properties": {
      "task_number": {
       "type": "integer"
      },
      "description": {
       "type": "string"
      },
      "status": {
       "type": "string",
       "enum": [
        "done",
        "partial",
        "failed",
        "skipped"
       ]
      },
      "verification_passed": {
       "type": "boolean"
      }
     }
    }
   },
   "files_modified": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "decisions_made": {
    "type": "array",
    "items": {
     "type": "string"
    }
   },
   "handoff_context": {
    "type": "object",
    "properties": {
     "key_outputs": {
      "type": "array",
      "items": {
       "type": "string"
      }
     },
     "conventions_established": {
      "type": "array",
      "items": {
       "type": "string"
      }
     },
     "open_questions": {
      "type": "array",
      "items": {
       "type": "string"
      }
     }
    }
   },
   "escalations": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "severity": {
       "type": "string",
       "enum": [
        "info",
        "warning",
        "blocker"
       ]
      },
      "type": {
       "type": "string"
      },
      "decision": {
       "type": "string"
      },
      "context": {
       "type": "string"
      },
      "status": {
       "type": "string",
       "enum": [
        "pending",
        "approved",
        "rejected",
        "deferred"
       ]
      }
     }
    }
   },
   "verification_results": {
    "type": "array",
    "items": {
     "type": "object",
     "properties": {
      "command": {
       "type": "string"
      },
      "exit_code": {
       "type": "integer"
      },
      "passed": {
       "type": "boolean"
      }
     }
    }
   }
  }
 },
 "finding": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Legion Review Finding",
  "description": "Schema for a single review finding in REVIEW.md",
  "$comment": "Completion Gate: a finding is complete when (1) it validates against this schema (all required fields present, enums match, id matches pattern ^F-\\d{3,}$); (2) status is one of open|fixed|accepted|deferred (no null, no missing); (3) if status=fixed, a cycle number is recorded; (4) if severity is blocker or critical, suggested_fix is non-empty. Validators MUST fail closed — unknown severity or status values are REJECTED, not coerced.",
  "type": "object",
  "required": [
   "id",
   "severity",
   "category",
   "description",
   "file",
   "status"
  ],
  "additionalProperties": false,
  "properties": {
   "id": {
    "type": "string",
    "pattern": "^F-\\d{3,}$"
   },
   "severity": {
    "type": "string",
    "enum": [
     "blocker",
     "critical",
     "major",
     "minor",
     "advisory"
    ]
   },
   "category": {
    "type": "string",
    "minLength": 1
   },
   "description": {
    "type": "string",
    "minLength": 1
   },
   "file": {
    "type": "string",
    "minLength": 1
   },
   "line_range": {
    "type": "string"
   },
   "suggested_fix": {
    "type": "string"
   },
   "agent": {
    "type": "string"
   },
   "status": {
    "type": "string",
    "enum": [
     "open",
     "fixed",
     "accepted",
     "deferred"
    ]
   },
   "cycle": {
    "type": "integer",
    "minimum": 1
   }
  },
  "allOf": [
   {
    "if": {
     "properties": {
      "status": {
       "const": "fixed"
      }
     },
     "required": [
      "status"
     ]
    },
    "then": {
     "required": [
      "cycle"
     ]
    }
   },
   {
    "if": {
     "properties": {
      "severity": {
       "enum": [
        "blocker",
        "critical"
       ]
      }
     },
     "required": [
      "severity"
     ]
    },
    "then": {
     "required": [
      "suggested_fix"
     ],
     "properties": {
      "suggested_fix": {
       "minLength": 1
      }
     }
    }
   }
  ]
 },
 "outcome": {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Legion Outcome Record",
  "description": "Schema for a single OUTCOMES.md record",
  "type": "object",
  "required": [
   "id",
   "date",
   "phase",
   "plan",
   "agent",
   "task_type",
   "outcome",
   "importance"
  ],
  "properties": {
   "id": {
    "type": "string",
    "pattern": "^O-\\d{3,}$"
   },
   "date": {
    "type": "string",
    "format": "date"
   },
   "branch": {
    "type": "string"
   },
   "phase": {
    "type": "integer"
   },
   "plan": {
    "type": "string",
    "pattern": "^\\d{2}-\\d{2}$"
   },
   "agent": {
    "type": "string"
   },
   "task_type": {
    "type": "string"
   },
   "outcome": {
    "type": "string",
    "enum": [
     "success",
     "partial",
     "failed"
    ]
   },
   "importance": {
    "type": "integer",
    "minimum": 1,
    "maximum": 5
   },
   "tags": {
    "type": "string"
   },
   "summary": {
    "type": "string"
   }
  }
 },
 "settings": {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Legion Settings",
  "type": "object",
  "additionalProperties": false,
  "properties": {
   "$schema": {
    "type": "string"
   },
   "control_mode": {
    "type": "string",
    "enum": [
     "autonomous",
     "guarded",
     "advisory",
     "surgical"
    ],
    "default": "guarded",
    "description": "Controls how strictly authority matrix rules are enforced. See .planning/config/control-modes.yaml for flag profiles."
   },
   "models": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
     "planning": {
      "type": "string"
     },
     "execution": {
      "type": "string"
     },
     "check": {
      "type": "string"
     },
     "planning_reasoning": {
      "type": "boolean",
      "default": false,
      "x-deprecated": true,
      "description": "DEPRECATED — see docs/audits/2026-04-16-legion-4-7/proposals/phase-d-deprecate-planning-reasoning.md. Slated for removal in v8.0."
     }
    },
    "required": [
     "planning",
     "execution",
     "check"
    ]
   },
   "planning": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
     "max_tasks_per_plan": {
      "type": "integer",
      "minimum": 1,
      "maximum": 5,
      "description": "Per-plan task cap only. Does not limit how many plans a phase may contain."
     },
     "architecture_proposals_default": {
      "type": "string",
      "enum": [
       "always",
       "prompt",
       "never"
      ]
     },
     "spec_pipeline_default": {
      "type": "string",
      "enum": [
       "always",
       "prompt",
       "never"
      ]
     }
    },
    "required": [
     "max_tasks_per_plan",
     "architecture_proposals_default",
     "spec_pipeline_default"
    ]
   },
   "execution": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
     "auto_commit": {
      "type": "boolean"
     },
     "commit_prefix": {
      "type": "string",
      "minLength": 1
     },
     "agent_personality_verbosity": {
      "type": "string",
      "enum": [
       "full",
       "condensed"
      ]
     },
     "use_worktrees": {
      "type": "boolean",
      "default": false,
      "description": "EXPERIMENTAL — opt-in worktree isolation per plan. See skills/wave-executor/SKILL.md for behavior. Defaults to false; flip only after running scripts/worktree-doctor.js (forthcoming, separate spec)."
     }
    },
    "required": [
     "auto_commit",
     "commit_prefix",
     "agent_personality_verbosity"
    ]
   },
   "review": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
     "default_mode": {
      "type": "string",
      "enum": [
       "classic",
       "panel"
      ]
     },
     "max_cycles": {
      "type": "integer",
      "minimum": 1,
      "maximum": 5
     },
     "evaluator_depth": {
      "type": "string",
      "enum": [
       "single",
       "multi-pass"
      ],
      "default": "multi-pass"
     },
     "polish": {
      "type": "boolean",
      "default": true,
      "description": "Enable post-review code polish step. When true, /legion:review runs a 4-pass cleanup after review passes."
     },
     "polish_scope": {
      "type": "string",
      "enum": [
       "changed",
       "dependents",
       "directory"
      ],
      "default": "dependents",
      "description": "Scope for review-integrated polish: changed files only, changed + dependents (default), or full directory."
     },
     "coverage_thresholds": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
       "overall": {
        "type": "integer",
        "minimum": 0,
        "maximum": 100
       },
       "business_logic": {
        "type": "integer",
        "minimum": 0,
        "maximum": 100
       },
       "api_routes": {
        "type": "integer",
        "minimum": 0,
        "maximum": 100
       }
      }
     }
    },
    "required": [
     "default_mode",
     "max_cycles"
    ]
   },
   "board": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
     "default_size": {
      "type": "integer",
      "minimum": 2,
      "maximum": 7
     },
     "min_size": {
      "type": "integer",
      "minimum": 2,
      "maximum": 5
     },
     "discussion_rounds": {
      "type": "integer",
      "minimum": 1,
      "maximum": 5
     },
     "assessment_timeout_ms": {
      "type": "integer",
      "minimum": 30000
     },
     "persist_artifacts": {
      "type": "boolean"
     }
    },
    "required": [
     "default_size",
     "min_size",
     "discussion_rounds",
     "assessment_timeout_ms",
     "persist_artifacts"
    ]
   },
   "dispatch": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
     "enabled": {
      "type": "boolean"
     },
     "fallback_to_internal": {
      "type": "boolean"
     },
     "timeout_ms": {
      "type": "integer",
      "minimum": 10000
     },
     "max_retries": {
      "type": "integer",
      "minimum": 0,
      "maximum": 3
     }
    },
    "required": [
     "enabled",
     "fallback_to_internal",
     "timeout_ms",
     "max_retries"
    ]
   },
   "memory": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
     "enabled": {
      "type": "boolean"
     },
     "project_scoped_only": {
      "type": "boolean",
      "const": true
     },
     "auto_prune": {
      "type": "boolean",
      "default": false
     },
     "prune_threshold": {
      "type": "integer",
      "minimum": 1,
      "default": 200
     },
     "prune_age_days": {
      "type": "integer",
      "minimum": 1,
      "default": 90
     }
    },
    "required": [
     "enabled",
     "project_scoped_only"
    ]
   },
   "integrations": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
     "github": {
      "type": "string",
      "enum": [
       "enabled",
       "disabled",
       "prompt"
      ]
     }
    },
    "required": [
     "github"
    ]
   }
  },
  "required": [
   "models",
   "planning",
   "execution",
   "review",
   "memory",
   "integrations",
   "dispatch"
  ]
 }
}

export const TEMPLATES: any = {
 "project": "# {project_name}\n\n## What This Is\n{project_description}\n\n## Core Value\n{value_proposition}\n\n## Who It's For\n{target_users}\n\n## Requirements\n\n### Validated\n(None yet — ship to validate)\n\n### Active\n{requirements_list}\n\n### Out of Scope\n{out_of_scope}\n\n## Constraints\n{constraints}\n\n## Key Decisions\n\n| Decision | Rationale | Outcome |\n|----------|-----------|---------|\n{decisions_table}\n\n## Architecture Influences\n{architecture_notes}\n\n---\n*Last updated: {date} after initialization*\n",
 "roadmap": "# {project_name} — Roadmap\n\n## Phases\n\n{phase_checklist}\n\n## Phase Details\n\n{phase_details_sections}\n\n<!-- Each phase detail block follows this pattern:\n### Phase N: {phase_name}\n**Goal**: {phase_goal}\n**Requirements**: {requirement_ids}\n**Recommended Agents**: {agent_ids}\n**Success Criteria**:\n{success_criteria_list}\n**Plans**: {estimated_plan_count}\n-->\n\n## Progress\n\n| Phase | Plans | Completed | Status |\n|-------|-------|-----------|--------|\n{progress_table}\n",
 "state": "# Project State\n\n## Current Position\n- **Phase**: 0 of {total_phases} (not started)\n- **Status**: Initialized — ready for `/legion:plan 1`\n- **Last Activity**: Project initialization ({date})\n\n## Progress\n```\n[{progress_bar}] {progress_percent}% — 0/{total_plans} plans complete\n```\n\n## Recent Decisions\n{recent_decisions}\n\n## Next Action\nRun `/legion:plan 1` to begin Phase 1: {first_phase_name}\n"
}

export const SETTINGS: any = {
 "control_mode": "guarded",
 "models": {
  "planning": "adapter_default",
  "execution": "adapter_default",
  "check": "adapter_default",
  "planning_reasoning": false
 },
 "planning": {
  "max_tasks_per_plan": 3,
  "architecture_proposals_default": "prompt",
  "spec_pipeline_default": "prompt"
 },
 "execution": {
  "auto_commit": true,
  "commit_prefix": "legion",
  "agent_personality_verbosity": "full",
  "use_worktrees": false
 },
 "review": {
  "default_mode": "panel",
  "max_cycles": 3,
  "evaluator_depth": "multi-pass",
  "coverage_thresholds": {
   "overall": 70,
   "business_logic": 90,
   "api_routes": 80
  }
 },
 "board": {
  "default_size": 5,
  "min_size": 3,
  "discussion_rounds": 2,
  "assessment_timeout_ms": 300000,
  "persist_artifacts": true
 },
 "dispatch": {
  "enabled": true,
  "fallback_to_internal": true,
  "timeout_ms": 300000,
  "max_retries": 1
 },
 "memory": {
  "enabled": true,
  "project_scoped_only": true,
  "auto_prune": false,
  "prune_threshold": 200,
  "prune_age_days": 90
 },
 "integrations": {
  "github": "prompt"
 }
}

export const CONTROL_MODES: any = {
 "autonomous": {
  "description": "Full agent autonomy — authority enforcement disabled, agents decide freely",
  "authority_enforcement": false,
  "domain_filtering": false,
  "human_approval_required": false,
  "file_scope_restriction": false,
  "read_only": false
 },
 "guarded": {
  "description": "Default — authority boundaries active, domain filtering on, human approval for out-of-scope",
  "authority_enforcement": true,
  "domain_filtering": true,
  "human_approval_required": true,
  "file_scope_restriction": false,
  "read_only": false
 },
 "advisory": {
  "description": "Read-only mode — agents suggest but don't execute, all findings shown unfiltered",
  "authority_enforcement": false,
  "domain_filtering": false,
  "human_approval_required": false,
  "file_scope_restriction": false,
  "read_only": true
 },
 "surgical": {
  "description": "Maximum restriction — agents only touch listed files, all changes require confirmation",
  "authority_enforcement": true,
  "domain_filtering": true,
  "human_approval_required": true,
  "file_scope_restriction": true,
  "read_only": false
 }
}

export const RUBRICS: any = {
 "testing-qa-verification-specialist": {
  "name": "Production Readiness",
  "criteria": [
   {
    "name": "Error handling",
    "check": "Edge cases covered, failures degrade gracefully, no silent swallowing"
   },
   {
    "name": "Real-world usage",
    "check": "Works outside happy path — unexpected input, missing state, concurrent access"
   },
   {
    "name": "Stability",
    "check": "No crashes, hangs, or resource leaks under normal operation"
   },
   {
    "name": "Integration correctness",
    "check": "Cross-file references resolve, dependencies exist, imports work"
   }
  ]
 },
 "testing-test-results-analyzer": {
  "name": "Verification & Test Quality",
  "criteria": [
   {
    "name": "Proof artifacts",
    "check": "Test files, verification scripts, or documented test runs exist for claims"
   },
   {
    "name": "Coverage breadth",
    "check": "All success criteria have corresponding verification, not just some"
   },
   {
    "name": "Assertion quality",
    "check": "Tests check meaningful behavior, not just \"no crash\"; before/after documented"
   },
   {
    "name": "Reproducibility",
    "check": "Verification steps can be repeated by someone else with same results"
   }
  ]
 },
 "testing-api-tester": {
  "name": "API Contract Compliance",
  "criteria": [
   {
    "name": "Endpoint correctness",
    "check": "Routes, methods, status codes match specification"
   },
   {
    "name": "Request/response validation",
    "check": "Payloads conform to schema, required fields present, types correct"
   },
   {
    "name": "Security boundaries",
    "check": "Auth required where expected, no unprotected sensitive endpoints"
   },
   {
    "name": "Error responses",
    "check": "API returns structured errors, not stack traces or generic 500s"
   }
  ]
 },
 "testing-workflow-optimizer": {
  "name": "Process Efficiency",
  "criteria": [
   {
    "name": "Workflow correctness",
    "check": "Steps execute in right order, no dead ends or unreachable paths"
   },
   {
    "name": "Redundancy",
    "check": "No duplicated logic, unnecessary steps, or circular dependencies"
   },
   {
    "name": "Automation opportunity",
    "check": "Manual steps that could be automated are flagged"
   },
   {
    "name": "Handoff clarity",
    "check": "Inputs and outputs between workflow steps are well-defined"
   }
  ]
 },
 "testing-performance-benchmarker": {
  "name": "Performance Characteristics",
  "criteria": [
   {
    "name": "Resource efficiency",
    "check": "No unnecessary file reads, API calls, or memory allocation"
   },
   {
    "name": "Scalability indicators",
    "check": "Approach handles growth (more agents, larger files, more phases)"
   },
   {
    "name": "Bottleneck risk",
    "check": "Sequential operations that could be parallelized"
   },
   {
    "name": "Cost awareness",
    "check": "Agent spawn count, model tier usage aligned with cost profile convention"
   }
  ]
 },
 "testing-tool-evaluator": {
  "name": "Dependency & Tool Health",
  "criteria": [
   {
    "name": "Dependency health",
    "check": "Referenced tools, libraries, or services are current and maintained"
   },
   {
    "name": "Compatibility",
    "check": "Dependencies work together, no version conflicts or breaking changes"
   },
   {
    "name": "License compliance",
    "check": "No restrictive licenses that conflict with project distribution"
   },
   {
    "name": "Alternatives considered",
    "check": "Better tools exist for the job and weren't evaluated"
   }
  ]
 },
 "design-brand-guardian": {
  "name": "Brand Consistency",
  "criteria": [
   {
    "name": "Visual identity",
    "check": "Colors, typography, spacing follow brand guidelines"
   },
   {
    "name": "Voice and tone",
    "check": "Copy and messaging match brand personality"
   },
   {
    "name": "Component consistency",
    "check": "UI elements use shared design tokens, not ad-hoc values"
   }
  ]
 },
 "design-ux-architect": {
  "name": "Accessibility & Structure",
  "criteria": [
   {
    "name": "WCAG compliance",
    "check": "Contrast ratios, keyboard navigation, screen reader support"
   },
   {
    "name": "Information architecture",
    "check": "Content is logically organized, navigation is intuitive"
   },
   {
    "name": "Semantic structure",
    "check": "HTML is semantic, headings are hierarchical, landmarks are correct"
   }
  ]
 },
 "design-ux-researcher": {
  "name": "Usability",
  "criteria": [
   {
    "name": "Nielsen's heuristics",
    "check": "Visibility of status, user control, consistency, error prevention"
   },
   {
    "name": "User flow completeness",
    "check": "Can users complete the intended task without getting stuck?"
   },
   {
    "name": "Cognitive load",
    "check": "Interface doesn't overwhelm — progressive disclosure, clear hierarchy"
   }
  ]
 },
 "engineering-senior-developer": {
  "name": "Code Architecture",
  "criteria": [
   {
    "name": "Pattern consistency",
    "check": "New code follows established project patterns and conventions"
   },
   {
    "name": "Abstraction quality",
    "check": "Right level of abstraction — not over-engineered, not duplicated"
   },
   {
    "name": "Maintainability",
    "check": "Code is readable, changes are localized, dependencies are explicit"
   },
   {
    "name": "Tech debt",
    "check": "New code doesn't introduce unnecessary technical debt"
   }
  ]
 },
 "engineering-backend-architect": {
  "name": "Backend Design",
  "criteria": [
   {
    "name": "Data modeling",
    "check": "Data structures are appropriate, relationships are clear"
   },
   {
    "name": "API design",
    "check": "Endpoints are RESTful/consistent, versioning considered"
   },
   {
    "name": "Infrastructure patterns",
    "check": "Deployment, scaling, and monitoring are addressed"
   }
  ]
 },
 "engineering-frontend-developer": {
  "name": "Frontend Quality",
  "criteria": [
   {
    "name": "Component structure",
    "check": "Components are reusable, props are typed, state is minimal"
   },
   {
    "name": "Rendering correctness",
    "check": "No unnecessary re-renders, loading states handled, errors caught"
   },
   {
    "name": "Responsive design",
    "check": "Layout works across viewport sizes, touch targets are adequate"
   }
  ]
 },
 "engineering-infrastructure-devops": {
  "name": "Operational Readiness",
  "criteria": [
   {
    "name": "CI/CD integration",
    "check": "Changes are testable in pipeline, no manual deployment steps"
   },
   {
    "name": "Configuration management",
    "check": "Secrets are not hardcoded, env-specific config is externalized"
   },
   {
    "name": "Monitoring & logging",
    "check": "Errors are observable, metrics are available for alerting"
   }
  ]
 },
 "product-sprint-prioritizer": {
  "name": "Prioritization Alignment",
  "criteria": [
   {
    "name": "Business value",
    "check": "Implementation delivers the intended user/business value"
   },
   {
    "name": "Scope discipline",
    "check": "No scope creep beyond what was planned"
   },
   {
    "name": "Dependency management",
    "check": "Cross-phase and external dependencies are tracked and resolved"
   }
  ]
 },
 "product-feedback-synthesizer": {
  "name": "User Alignment",
  "criteria": [
   {
    "name": "User need coverage",
    "check": "Implementation addresses the core user pain point or request"
   },
   {
    "name": "Feedback incorporation",
    "check": "Known user feedback was considered in the implementation"
   },
   {
    "name": "Satisfaction drivers",
    "check": "The output is likely to improve user satisfaction"
   }
  ]
 },
 "project-manager-senior": {
  "name": "Delivery Management",
  "criteria": [
   {
    "name": "Scope completeness",
    "check": "All planned deliverables are present"
   },
   {
    "name": "Risk mitigation",
    "check": "Known risks were addressed or documented"
   },
   {
    "name": "Documentation",
    "check": "Handoff documentation is sufficient for the next phase"
   }
  ]
 },
 "project-management-project-shepherd": {
  "name": "Process Compliance",
  "criteria": [
   {
    "name": "Methodology adherence",
    "check": "Work followed the established workflow (plan → build → review)"
   },
   {
    "name": "Artifact quality",
    "check": "State files, summaries, and plans are complete and accurate"
   },
   {
    "name": "Handoff readiness",
    "check": "Next phase can start without ambiguity about what was done"
   }
  ]
 }
}

export const DEFAULT_RUBRICS: any = {
 "Testing": {
  "name": "General QA",
  "criteria": [
   {
    "name": "Correctness",
    "check": "Correctness"
   },
   {
    "name": "Completeness",
    "check": "completeness"
   },
   {
    "name": "Consistency",
    "check": "consistency"
   }
  ]
 },
 "Design": {
  "name": "General Design Review",
  "criteria": [
   {
    "name": "Visual quality",
    "check": "Visual quality"
   },
   {
    "name": "Usability",
    "check": "usability"
   },
   {
    "name": "Accessibility",
    "check": "accessibility"
   }
  ]
 },
 "Engineering": {
  "name": "General Code Review",
  "criteria": [
   {
    "name": "Correctness",
    "check": "Correctness"
   },
   {
    "name": "Patterns",
    "check": "patterns"
   },
   {
    "name": "Maintainability",
    "check": "maintainability"
   }
  ]
 },
 "Product": {
  "name": "General Product Review",
  "criteria": [
   {
    "name": "Value delivery",
    "check": "Value delivery"
   },
   {
    "name": "Scope",
    "check": "scope"
   },
   {
    "name": "Alignment",
    "check": "alignment"
   }
  ]
 },
 "Project Management": {
  "name": "General Delivery Review",
  "criteria": [
   {
    "name": "Completeness",
    "check": "Completeness"
   },
   {
    "name": "Documentation",
    "check": "documentation"
   },
   {
    "name": "Handoff",
    "check": "handoff"
   }
  ]
 }
}

export const DOMAINS: any = {
 "engineering-security-engineer": [
  "security",
  "owasp",
  "stride",
  "vulnerability-assessment",
  "pentest",
  "threat-modeling",
  "secure-coding"
 ],
 "engineering-infrastructure-devops": [
  "ci-cd",
  "deployment",
  "infrastructure-as-code",
  "containers",
  "orchestration",
  "docker",
  "kubernetes",
  "infrastructure",
  "system-reliability",
  "monitoring",
  "cloud-management",
  "cost-optimization"
 ],
 "engineering-backend-architect": [
  "backend-architecture",
  "database-design",
  "api-design",
  "microservices",
  "system-design",
  "data-modeling"
 ],
 "engineering-frontend-developer": [
  "frontend-architecture",
  "ui-components",
  "state-management",
  "client-side-routing",
  "react",
  "vue",
  "angular"
 ],
 "engineering-ai-engineer": [
  "ai-integration",
  "llm-prompts",
  "model-selection",
  "ai-testing",
  "ml-ops",
  "data-pipelines"
 ],
 "engineering-mobile-app-builder": [
  "mobile-architecture",
  "ios",
  "android",
  "react-native",
  "flutter",
  "cross-platform"
 ],
 "engineering-rapid-prototyper": [
  "rapid-prototyping",
  "spike-solutions",
  "proof-of-concept",
  "mvp",
  "experimentation"
 ],
 "engineering-laravel-specialist": [
  "laravel",
  "php",
  "eloquent",
  "blade",
  "artisan",
  "livewire",
  "fluxui"
 ],
 "engineering-senior-developer": [
  "full-stack",
  "refactoring",
  "code-quality",
  "reliability"
 ],
 "testing-qa-verification-specialist": [
  "production-readiness",
  "edge-cases",
  "failure-modes",
  "risk-assessment",
  "verification",
  "test-coverage",
  "proof-artifacts",
  "evidence-gathering"
 ],
 "testing-api-tester": [
  "api-testing",
  "contract-testing",
  "endpoint-validation"
 ],
 "testing-performance-benchmarker": [
  "performance",
  "load-testing",
  "benchmarking",
  "optimization"
 ],
 "testing-workflow-optimizer": [
  "workflow-efficiency",
  "process-automation",
  "execution-optimization"
 ],
 "testing-test-results-analyzer": [
  "test-analysis",
  "failure-diagnosis",
  "root-cause-analysis"
 ],
 "testing-tool-evaluator": [
  "tool-evaluation",
  "dependency-assessment",
  "technology-selection"
 ],
 "design-brand-guardian": [
  "brand-consistency",
  "visual-identity",
  "tone-voice",
  "brand-strategy"
 ],
 "design-ux-architect": [
  "accessibility",
  "wcag",
  "information-architecture",
  "navigation",
  "css-systems",
  "layout-frameworks"
 ],
 "design-ux-researcher": [
  "usability-testing",
  "user-research",
  "heuristics",
  "behavior-analysis"
 ],
 "design-visual-storyteller": [
  "visual-design",
  "illustration",
  "motion",
  "visual-narratives",
  "multimedia-content"
 ],
 "design-ui-designer": [
  "ui-design",
  "component-design",
  "design-systems",
  "component-libraries"
 ],
 "design-whimsy-injector": [
  "microinteractions",
  "delight-design",
  "animation",
  "creative-direction",
  "personality"
 ],
 "marketing-content-social-strategist": [
  "cross-platform-strategy",
  "platform-selection",
  "content-mix",
  "channel-allocation",
  "content-strategy",
  "copywriting",
  "editorial-calendar",
  "brand-storytelling"
 ],
 "marketing-growth-hacker": [
  "growth-hacking",
  "user-acquisition",
  "viral-loops",
  "conversion-funnels",
  "experimentation"
 ],
 "marketing-social-platform-specialist": [
  "twitter",
  "real-time-engagement",
  "thought-leadership",
  "social-listening",
  "instagram",
  "visual-content",
  "community-building",
  "reels",
  "aesthetic-curation"
 ],
 "marketing-app-store-optimizer": [
  "aso",
  "app-store",
  "conversion-optimization",
  "app-marketing",
  "keyword-optimization"
 ],
 "product-sprint-prioritizer": [
  "sprint-planning",
  "prioritization",
  "backlog-grooming",
  "resource-allocation"
 ],
 "product-feedback-synthesizer": [
  "user-feedback",
  "sentiment-analysis",
  "product-insights",
  "feature-requests",
  "feedback-triage"
 ],
 "product-trend-researcher": [
  "market-research",
  "competitive-analysis",
  "trend-identification",
  "opportunity-assessment",
  "industry-intelligence"
 ],
 "product-technical-writer": [
  "api-documentation",
  "user-guides",
  "readme-generation",
  "developer-docs",
  "tutorials-and-examples",
  "release-notes",
  "documentation-clarity",
  "stale-doc-detection"
 ],
 "project-manager-senior": [
  "task-breakdown",
  "spec-to-tasks",
  "scope-management",
  "sprint-execution",
  "implementation-planning"
 ],
 "project-management-project-shepherd": [
  "project-coordination",
  "timeline-management",
  "stakeholder-alignment",
  "risk-management",
  "cross-functional"
 ],
 "project-management-studio-producer": [
  "portfolio-management",
  "creative-direction",
  "resource-allocation",
  "strategic-planning",
  "executive-oversight"
 ],
 "project-management-studio-operations": [
  "studio-ops",
  "process-optimization",
  "resource-coordination",
  "productivity",
  "operational-excellence"
 ],
 "project-management-experiment-tracker": [
  "experiment-design",
  "ab-testing",
  "hypothesis-validation",
  "data-driven-decisions",
  "experiment-tracking"
 ],
 "support-finance-tracker": [
  "financial-planning",
  "budget-management",
  "cash-flow",
  "investment-analysis",
  "financial-risk"
 ],
 "support-legal-compliance-checker": [
  "legal-compliance",
  "risk-assessment",
  "policy-development",
  "regulatory",
  "gdpr-privacy"
 ],
 "support-executive-summary-generator": [
  "executive-summaries",
  "strategy-consulting",
  "c-suite-reporting",
  "business-communication",
  "frameworks"
 ],
 "support-support-responder": [
  "customer-support",
  "ticket-management",
  "issue-resolution",
  "user-onboarding"
 ],
 "visionos-spatial-engineer": [
  "visionos",
  "spatial-computing",
  "swiftui-volumetric",
  "liquid-glass",
  "realitykit"
 ],
 "macos-spatial-metal-engineer": [
  "metal",
  "swift",
  "3d-rendering",
  "macos",
  "vision-pro"
 ],
 "xr-interface-architect": [
  "spatial-ux",
  "xr-interfaces",
  "comfort-design",
  "3d-navigation",
  "presence-optimization"
 ],
 "xr-immersive-developer": [
  "webxr",
  "ar-vr",
  "browser-3d",
  "immersive-apps",
  "cross-platform-xr"
 ],
 "xr-cockpit-interaction-specialist": [
  "xr-cockpit",
  "spatial-controls",
  "immersive-ui",
  "cockpit-design",
  "high-presence"
 ],
 "terminal-integration-specialist": [
  "terminal-emulation",
  "swiftterm",
  "text-rendering",
  "swift-ui",
  "vt100"
 ],
 "agents-orchestrator": [
  "orchestration",
  "pipeline-management",
  "workflow-automation",
  "agent-coordination",
  "dev-qa-loops",
  "agent-communication"
 ],
 "data-analytics-engineer": [
  "data-pipelines",
  "etl",
  "data-quality",
  "data-warehouse",
  "data-engineering",
  "dashboards",
  "kpi-reporting",
  "business-intelligence",
  "statistical-analyses"
 ],
 "lsp-index-engineer": [
  "lsp",
  "code-intelligence",
  "semantic-indexing",
  "language-servers",
  "developer-tooling"
 ],
 "polymath": [
  "exploration",
  "clarification",
  "research-first",
  "structured-questions",
  "gap-detection"
 ]
}
