// Generated by triad/scripts/gen_legion_exec.ts from Legion (MIT; see triad/LEGION-NOTICE.md). Do not edit.
export const ESCALATION_PROTOCOL: any = {
 "escalation_format": {
  "required_fields": [
   "severity",
   "type",
   "decision",
   "context"
  ],
  "optional_fields": [
   "alternatives",
   "affected_files",
   "related_domain"
  ]
 },
 "severity_levels": [
  "info",
  "warning",
  "blocker"
 ],
 "escalation_types": {
  "architecture": {
   "default_severity": "warning"
  },
  "dependency": {
   "default_severity": "blocker"
  },
  "scope": {
   "default_severity": "warning"
  },
  "schema": {
   "default_severity": "blocker"
  },
  "api": {
   "default_severity": "blocker"
  },
  "deletion": {
   "default_severity": "blocker"
  },
  "infrastructure": {
   "default_severity": "blocker"
  },
  "quality": {
   "default_severity": "blocker"
  }
 },
 "control_mode_behaviors": {
  "autonomous": {
   "override_severity": "info",
   "behavior": [
    "All escalations treated as info severity regardless of declared severity",
    "Logged to SUMMARY.md for post-build review",
    "Agent is never instructed to halt on out-of-scope actions; if escalation blocks appear in output, they are logged as info-level observations for post-build review"
   ]
  },
  "guarded": {
   "override_severity": null,
   "behavior": [
    "info escalations logged, execution continues",
    "warning escalations logged and highlighted, execution continues",
    "blocker escalations halt the current task, user prompted for decision"
   ]
  },
  "advisory": {
   "override_severity": "info",
   "behavior": [
    "All agent actions are informational (agents suggest, do not execute)",
    "Every out-of-scope observation logged as info-level escalation",
    "No halting (nothing to halt — agents are not modifying anything)"
   ]
  },
  "surgical": {
   "override_severity": null,
   "behavior": [
    "Any file not in the plan's files_modified triggers automatic blocker escalation",
    "Declared severity is respected but never downgraded below warning",
    "Out-of-scope file access auto-generates a blocker even without explicit <escalation> block"
   ],
   "auto_escalate_file_scope": true
  }
 },
 "resolution": {
  "statuses": [
   "pending",
   "approved",
   "rejected",
   "deferred"
  ]
 }
}

export const SUMMARY_EXPORT_STANDARD: any = {
 "required_sections": [
  "## Completed Tasks",
  "## Files Modified",
  "## Handoff Context",
  "## Verification Results"
 ],
 "conditional_sections": [
  "## Escalations",
  "## Decisions Made",
  "## Open Questions"
 ]
}
