// Embeds the Legion data the build executor needs beyond gen_legion.ts. Reads a
// Legion checkout as plain files; runs none of its code.
//
//   node --experimental-strip-types --no-warnings triad/scripts/gen_legion_exec.ts <legion-dir>
//
// Writes:
//   triad/hooks/legion/personasfull.ts   full agents/*.md bodies (execution.agent_personality_verbosity full)
//   triad/hooks/legion/execdata.ts       escalation-protocol.yaml and the agent-communication
//                                        summary_export_standard
//
// Legion is MIT licensed; see triad/LEGION-NOTICE.md.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseYaml, splitFrontmatter } from '../hooks/legion/yaml.ts'

const legion = process.argv[2]
if (!legion) throw new Error('usage: gen_legion_exec.ts <legion-dir>')
const triad = join(dirname(fileURLToPath(import.meta.url)), '..')
const read = (p: string) => readFileSync(join(legion, p), 'utf8')
const HEADER = '// Generated by triad/scripts/gen_legion_exec.ts from Legion (MIT; see triad/LEGION-NOTICE.md). Do not edit.\n'

// Legion paths and commands that do not exist in Triad, rewritten as in personas.ts.
const adapt = (body: string) => body
  .replaceAll('Follow `skills/agent-registry/MANDATORY-PERSONA-CONTRACT.md`.', 'Follow the persona contract below (it is the same for every persona).')
  .replace(/\/legion:([a-z-]+)/g, '/triad:$1')
const bodies: Record<string, string> = {}
for (const f of readdirSync(join(legion, 'agents')).filter(f => f.endsWith('.md')).sort()) bodies[f.replace(/\.md$/, '')] = adapt(splitFrontmatter(read(`agents/${f}`)).body.trim())
writeFileSync(join(triad, 'hooks/legion/personasfull.ts'), HEADER + `export const PERSONA_BODIES: Record<string, string> = ${JSON.stringify(bodies, null, 1)}\n`)

const esc = parseYaml(read('.planning/config/escalation-protocol.yaml')) as any
const comm = parseYaml(read('.planning/config/agent-communication.yaml')) as any
const protocol = {
  escalation_format: { required_fields: esc.escalation_format.required_fields, optional_fields: esc.escalation_format.optional_fields },
  severity_levels: Object.keys(esc.severity_levels),
  escalation_types: Object.fromEntries(Object.entries<any>(esc.escalation_types).map(([k, v]) => [k, { default_severity: v.default_severity }])),
  control_mode_behaviors: Object.fromEntries(Object.entries<any>(esc.control_mode_behaviors).map(([k, v]) => [k, { override_severity: v.override_severity ?? null, behavior: v.behavior ?? [], ...(v.auto_escalate_file_scope ? { auto_escalate_file_scope: true } : {}) }])),
  resolution: { statuses: esc.resolution.statuses },
}
const standard = { required_sections: comm.summary_export_standard.required_sections, conditional_sections: comm.summary_export_standard.conditional_sections.map((c: any) => c.section) }
writeFileSync(join(triad, 'hooks/legion/execdata.ts'), HEADER +
  `export const ESCALATION_PROTOCOL: any = ${JSON.stringify(protocol, null, 1)}\n\nexport const SUMMARY_EXPORT_STANDARD: any = ${JSON.stringify(standard, null, 1)}\n`)
console.log(`persona bodies ${Object.keys(bodies).length}, escalation types ${Object.keys(protocol.escalation_types).length}`)
